name: covid_19_app
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  flutter_flavor: ^3.1.1
  go_router: ^7.0.1
  flutter_spinkit: ^5.2.0
  google_fonts: ^6.1.0
  intl: ^0.18.1
  flutter_svg: ^1.1.5
  fluttertoast: ^8.2.4
  path_provider: ^2.1.2
  device_info_plus: ^9.1.2
  flutter_switch: ^0.3.2
  d_chart: ^2.6.7
  infinite_carousel: ^1.0.3
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:  
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/data/

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
