// To parse this JSON data, do
//
//     final statesCurrent = statesCurrentFromJson(jsonString);

import 'dart:convert';

List<StatesCurrent> statesCurrentFromJson(String str) =>
    List<StatesCurrent>.from(
        json.decode(str).map((x) => StatesCurrent.fromJson(x)));

String statesCurrentToJson(List<StatesCurrent> data) =>
    json.encode(List<dynamic>.from(data.map((x) => x.toJson())));

class StatesCurrent {
  int date;
  String state;
  int positive;
  int? probableCases;
  int? negative;
  int? pending;
  String totalTestResultsSource;
  int totalTestResults;
  int? hospitalizedCurrently;
  int? hospitalizedCumulative;
  int? inIcuCurrently;
  int? inIcuCumulative;
  int? onVentilatorCurrently;
  int? onVentilatorCumulative;
  int? recovered;
  String? lastUpdateEt;
  String? dateModified;
  String? checkTimeEt;
  int death;
  int? hospitalized;
  int? hospitalizedDischarged;
  String? dateChecked;
  int? totalTestsViral;
  int? positiveTestsViral;
  int? negativeTestsViral;
  int? positiveCasesViral;
  int? deathConfirmed;
  int? deathProbable;
  int? totalTestEncountersViral;
  int? totalTestsPeopleViral;
  int? totalTestsAntibody;
  int? positiveTestsAntibody;
  int? negativeTestsAntibody;
  int? totalTestsPeopleAntibody;
  int? positiveTestsPeopleAntibody;
  int? negativeTestsPeopleAntibody;
  int? totalTestsPeopleAntigen;
  int? positiveTestsPeopleAntigen;
  int? totalTestsAntigen;
  int? positiveTestsAntigen;
  String fips;
  int positiveIncrease;
  int negativeIncrease;
  int total;
  int totalTestResultsIncrease;
  int posNeg;
  dynamic dataQualityGrade;
  int deathIncrease;
  int hospitalizedIncrease;
  String hash;
  int commercialScore;
  int negativeRegularScore;
  int negativeScore;
  int positiveScore;
  int score;
  String grade;

  StatesCurrent({
    required this.date,
    required this.state,
    required this.positive,
    required this.probableCases,
    required this.negative,
    required this.pending,
    required this.totalTestResultsSource,
    required this.totalTestResults,
    required this.hospitalizedCurrently,
    required this.hospitalizedCumulative,
    required this.inIcuCurrently,
    required this.inIcuCumulative,
    required this.onVentilatorCurrently,
    required this.onVentilatorCumulative,
    required this.recovered,
    required this.lastUpdateEt,
    required this.dateModified,
    required this.checkTimeEt,
    required this.death,
    required this.hospitalized,
    required this.hospitalizedDischarged,
    required this.dateChecked,
    required this.totalTestsViral,
    required this.positiveTestsViral,
    required this.negativeTestsViral,
    required this.positiveCasesViral,
    required this.deathConfirmed,
    required this.deathProbable,
    required this.totalTestEncountersViral,
    required this.totalTestsPeopleViral,
    required this.totalTestsAntibody,
    required this.positiveTestsAntibody,
    required this.negativeTestsAntibody,
    required this.totalTestsPeopleAntibody,
    required this.positiveTestsPeopleAntibody,
    required this.negativeTestsPeopleAntibody,
    required this.totalTestsPeopleAntigen,
    required this.positiveTestsPeopleAntigen,
    required this.totalTestsAntigen,
    required this.positiveTestsAntigen,
    required this.fips,
    required this.positiveIncrease,
    required this.negativeIncrease,
    required this.total,
    required this.totalTestResultsIncrease,
    required this.posNeg,
    required this.dataQualityGrade,
    required this.deathIncrease,
    required this.hospitalizedIncrease,
    required this.hash,
    required this.commercialScore,
    required this.negativeRegularScore,
    required this.negativeScore,
    required this.positiveScore,
    required this.score,
    required this.grade,
  });

  factory StatesCurrent.fromJson(Map<String, dynamic> json) => StatesCurrent(
        date: json["date"],
        state: json["state"],
        positive: json["positive"],
        probableCases: json["probableCases"],
        negative: json["negative"],
        pending: json["pending"],
        totalTestResultsSource: json["totalTestResultsSource"],
        totalTestResults: json["totalTestResults"],
        hospitalizedCurrently: json["hospitalizedCurrently"],
        hospitalizedCumulative: json["hospitalizedCumulative"],
        inIcuCurrently: json["inIcuCurrently"],
        inIcuCumulative: json["inIcuCumulative"],
        onVentilatorCurrently: json["onVentilatorCurrently"],
        onVentilatorCumulative: json["onVentilatorCumulative"],
        recovered: json["recovered"],
        lastUpdateEt: json["lastUpdateEt"],
        dateModified: json["dateModified"],
        checkTimeEt: json["checkTimeEt"],
        death: json["death"],
        hospitalized: json["hospitalized"],
        hospitalizedDischarged: json["hospitalizedDischarged"],
        dateChecked: json["dateChecked"],
        totalTestsViral: json["totalTestsViral"],
        positiveTestsViral: json["positiveTestsViral"],
        negativeTestsViral: json["negativeTestsViral"],
        positiveCasesViral: json["positiveCasesViral"],
        deathConfirmed: json["deathConfirmed"],
        deathProbable: json["deathProbable"],
        totalTestEncountersViral: json["totalTestEncountersViral"],
        totalTestsPeopleViral: json["totalTestsPeopleViral"],
        totalTestsAntibody: json["totalTestsAntibody"],
        positiveTestsAntibody: json["positiveTestsAntibody"],
        negativeTestsAntibody: json["negativeTestsAntibody"],
        totalTestsPeopleAntibody: json["totalTestsPeopleAntibody"],
        positiveTestsPeopleAntibody: json["positiveTestsPeopleAntibody"],
        negativeTestsPeopleAntibody: json["negativeTestsPeopleAntibody"],
        totalTestsPeopleAntigen: json["totalTestsPeopleAntigen"],
        positiveTestsPeopleAntigen: json["positiveTestsPeopleAntigen"],
        totalTestsAntigen: json["totalTestsAntigen"],
        positiveTestsAntigen: json["positiveTestsAntigen"],
        fips: json["fips"],
        positiveIncrease: json["positiveIncrease"],
        negativeIncrease: json["negativeIncrease"],
        total: json["total"],
        totalTestResultsIncrease: json["totalTestResultsIncrease"],
        posNeg: json["posNeg"],
        dataQualityGrade: json["dataQualityGrade"],
        deathIncrease: json["deathIncrease"],
        hospitalizedIncrease: json["hospitalizedIncrease"],
        hash: json["hash"],
        commercialScore: json["commercialScore"],
        negativeRegularScore: json["negativeRegularScore"],
        negativeScore: json["negativeScore"],
        positiveScore: json["positiveScore"],
        score: json["score"],
        grade: json["grade"],
      );

  Map<String, dynamic> toJson() => {
        "date": date,
        "state": state,
        "positive": positive,
        "probableCases": probableCases,
        "negative": negative,
        "pending": pending,
        "totalTestResultsSource": [totalTestResultsSource],
        "totalTestResults": totalTestResults,
        "hospitalizedCurrently": hospitalizedCurrently,
        "hospitalizedCumulative": hospitalizedCumulative,
        "inIcuCurrently": inIcuCurrently,
        "inIcuCumulative": inIcuCumulative,
        "onVentilatorCurrently": onVentilatorCurrently,
        "onVentilatorCumulative": onVentilatorCumulative,
        "recovered": recovered,
        "lastUpdateEt": lastUpdateEt,
        "dateModified": dateModified,
        "checkTimeEt": checkTimeEt,
        "death": death,
        "hospitalized": hospitalized,
        "hospitalizedDischarged": hospitalizedDischarged,
        "dateChecked": dateChecked,
        "totalTestsViral": totalTestsViral,
        "positiveTestsViral": positiveTestsViral,
        "negativeTestsViral": negativeTestsViral,
        "positiveCasesViral": positiveCasesViral,
        "deathConfirmed": deathConfirmed,
        "deathProbable": deathProbable,
        "totalTestEncountersViral": totalTestEncountersViral,
        "totalTestsPeopleViral": totalTestsPeopleViral,
        "totalTestsAntibody": totalTestsAntibody,
        "positiveTestsAntibody": positiveTestsAntibody,
        "negativeTestsAntibody": negativeTestsAntibody,
        "totalTestsPeopleAntibody": totalTestsPeopleAntibody,
        "positiveTestsPeopleAntibody": positiveTestsPeopleAntibody,
        "negativeTestsPeopleAntibody": negativeTestsPeopleAntibody,
        "totalTestsPeopleAntigen": totalTestsPeopleAntigen,
        "positiveTestsPeopleAntigen": positiveTestsPeopleAntigen,
        "totalTestsAntigen": totalTestsAntigen,
        "positiveTestsAntigen": positiveTestsAntigen,
        "fips": fips,
        "positiveIncrease": positiveIncrease,
        "negativeIncrease": negativeIncrease,
        "total": total,
        "totalTestResultsIncrease": totalTestResultsIncrease,
        "posNeg": posNeg,
        "dataQualityGrade": dataQualityGrade,
        "deathIncrease": deathIncrease,
        "hospitalizedIncrease": hospitalizedIncrease,
        "hash": hash,
        "commercialScore": commercialScore,
        "negativeRegularScore": negativeRegularScore,
        "negativeScore": negativeScore,
        "positiveScore": positiveScore,
        "score": score,
        "grade": grade,
      };
}
